XBE_TITLE = xbox_oc
GEN_XISO = $(XBE_TITLE).iso
SRCS = $(CURDIR)/main.c
NXDK_DIR ?= $(CURDIR)/../..

NXDK_SDL = y

CFLAGS += -Og -Wall -Wextra -pedantic
CXXFLAGS += -Og -Wall -Wextra -pedantic

NXDK_CFLAGS += -Og -Wall -Wextra -pedantic
NXDK_CXXFLAGS += -Og -Wall -Wextra -pedantic

include $(NXDK_DIR)/Makefile
